/* soapStub.h
   Generated by gSOAP 2.8.45 for ImageUpload.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20845
# error "GSOAP VERSION 20845 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumeration Types                                                          *
 *                                                                            *
\******************************************************************************/


/* ImageUpload.h:137 */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
/* xsd:boolean */
enum xsd__boolean {
	xsd__boolean__false_ = 0,
	xsd__boolean__true_ = 1
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct xsd__base64Binary;	/* ImageUpload.h:131 */
struct _ns1__GetSysTime;	/* ImageUpload.h:167 */
struct _ns1__GetSysTimeResponse;	/* ImageUpload.h:181 */
struct _ns1__UpLoadImg;	/* ImageUpload.h:197 */
struct _ns1__UpLoadImgResponse;	/* ImageUpload.h:217 */
struct _ns1__SetCurrentBillWay;	/* ImageUpload.h:233 */
struct _ns1__SetCurrentBillWayResponse;	/* ImageUpload.h:251 */
struct _ns1__GetCurrentImg;	/* ImageUpload.h:265 */
struct _ns1__GetCurrentImgResponse;	/* ImageUpload.h:281 */
struct __ns1__GetSysTime;	/* ImageUpload.h:432 */
struct __ns1__UpLoadImg;	/* ImageUpload.h:490 */
struct __ns1__SetCurrentBillWay;	/* ImageUpload.h:548 */
struct __ns1__GetCurrentImg;	/* ImageUpload.h:606 */
struct __ns1__GetSysTime_;	/* ImageUpload.h:664 */
struct __ns1__UpLoadImg_;	/* ImageUpload.h:722 */
struct __ns1__SetCurrentBillWay_;	/* ImageUpload.h:780 */
struct __ns1__GetCurrentImg_;	/* ImageUpload.h:838 */

/* ImageUpload.h:131 */
#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
/* binary data attached as MTOM/MIME/DIME attachment or included as *`xsd:base64Binary`* base64: */
struct xsd__base64Binary {
        unsigned char *__ptr;
        int __size;
        /** Optional element 'id' of XSD type 'xsd:string' */
        char *id;
        /** Optional element 'type' of XSD type 'xsd:string' */
        char *type;
        /** Optional element 'options' of XSD type 'xsd:string' */
        char *options;
};
#endif

/* ImageUpload.h:167 */
#ifndef SOAP_TYPE__ns1__GetSysTime
#define SOAP_TYPE__ns1__GetSysTime (12)
/* complex XSD type 'ns1:GetSysTime': */
struct _ns1__GetSysTime {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* ImageUpload.h:181 */
#ifndef SOAP_TYPE__ns1__GetSysTimeResponse
#define SOAP_TYPE__ns1__GetSysTimeResponse (13)
/* complex XSD type 'ns1:GetSysTimeResponse': */
struct _ns1__GetSysTimeResponse {
        /** Optional element 'ns1:GetSysTimeResult' of XSD type 'xsd:string' */
        char *GetSysTimeResult;
};
#endif

/* ImageUpload.h:197 */
#ifndef SOAP_TYPE__ns1__UpLoadImg
#define SOAP_TYPE__ns1__UpLoadImg (14)
/* complex XSD type 'ns1:UpLoadImg': */
struct _ns1__UpLoadImg {
        /** Optional element 'ns1:ID' of XSD type 'xsd:string' */
        char *ID;
        /** Optional element 'ns1:pic' of XSD type 'xsd:base64Binary' */
        struct xsd__base64Binary pic;
        /** Optional element 'ns1:timeStr' of XSD type 'xsd:string' */
        char *timeStr;
};
#endif

/* ImageUpload.h:217 */
#ifndef SOAP_TYPE__ns1__UpLoadImgResponse
#define SOAP_TYPE__ns1__UpLoadImgResponse (15)
/* complex XSD type 'ns1:UpLoadImgResponse': */
struct _ns1__UpLoadImgResponse {
        /** Required element 'ns1:UpLoadImgResult' of XSD type 'xsd:boolean' */
        enum xsd__boolean UpLoadImgResult;
};
#endif

/* ImageUpload.h:233 */
#ifndef SOAP_TYPE__ns1__SetCurrentBillWay
#define SOAP_TYPE__ns1__SetCurrentBillWay (16)
/* complex XSD type 'ns1:SetCurrentBillWay': */
struct _ns1__SetCurrentBillWay {
        /** Optional element 'ns1:ID' of XSD type 'xsd:string' */
        char *ID;
        /** Optional element 'ns1:billWay' of XSD type 'xsd:string' */
        char *billWay;
};
#endif

/* ImageUpload.h:251 */
#ifndef SOAP_TYPE__ns1__SetCurrentBillWayResponse
#define SOAP_TYPE__ns1__SetCurrentBillWayResponse (17)
/* complex XSD type 'ns1:SetCurrentBillWayResponse': */
struct _ns1__SetCurrentBillWayResponse {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* ImageUpload.h:265 */
#ifndef SOAP_TYPE__ns1__GetCurrentImg
#define SOAP_TYPE__ns1__GetCurrentImg (18)
/* complex XSD type 'ns1:GetCurrentImg': */
struct _ns1__GetCurrentImg {
        /** Optional element 'ns1:ID' of XSD type 'xsd:string' */
        char *ID;
};
#endif

/* ImageUpload.h:281 */
#ifndef SOAP_TYPE__ns1__GetCurrentImgResponse
#define SOAP_TYPE__ns1__GetCurrentImgResponse (19)
/* complex XSD type 'ns1:GetCurrentImgResponse': */
struct _ns1__GetCurrentImgResponse {
        /** Optional element 'ns1:GetCurrentImgResult' of XSD type 'xsd:base64Binary' */
        struct xsd__base64Binary GetCurrentImgResult;
};
#endif

/* ImageUpload.h:432 */
#ifndef SOAP_TYPE___ns1__GetSysTime
#define SOAP_TYPE___ns1__GetSysTime (23)
/* Wrapper: */
struct __ns1__GetSysTime {
        /** Optional element 'ns1:GetSysTime' of XSD type 'ns1:GetSysTime' */
        struct _ns1__GetSysTime *ns1__GetSysTime;
};
#endif

/* ImageUpload.h:490 */
#ifndef SOAP_TYPE___ns1__UpLoadImg
#define SOAP_TYPE___ns1__UpLoadImg (27)
/* Wrapper: */
struct __ns1__UpLoadImg {
        /** Optional element 'ns1:UpLoadImg' of XSD type 'ns1:UpLoadImg' */
        struct _ns1__UpLoadImg *ns1__UpLoadImg;
};
#endif

/* ImageUpload.h:548 */
#ifndef SOAP_TYPE___ns1__SetCurrentBillWay
#define SOAP_TYPE___ns1__SetCurrentBillWay (31)
/* Wrapper: */
struct __ns1__SetCurrentBillWay {
        /** Optional element 'ns1:SetCurrentBillWay' of XSD type 'ns1:SetCurrentBillWay' */
        struct _ns1__SetCurrentBillWay *ns1__SetCurrentBillWay;
};
#endif

/* ImageUpload.h:606 */
#ifndef SOAP_TYPE___ns1__GetCurrentImg
#define SOAP_TYPE___ns1__GetCurrentImg (35)
/* Wrapper: */
struct __ns1__GetCurrentImg {
        /** Optional element 'ns1:GetCurrentImg' of XSD type 'ns1:GetCurrentImg' */
        struct _ns1__GetCurrentImg *ns1__GetCurrentImg;
};
#endif

/* ImageUpload.h:664 */
#ifndef SOAP_TYPE___ns1__GetSysTime_
#define SOAP_TYPE___ns1__GetSysTime_ (37)
/* Wrapper: */
struct __ns1__GetSysTime_ {
        /** Optional element 'ns1:GetSysTime' of XSD type 'ns1:GetSysTime' */
        struct _ns1__GetSysTime *ns1__GetSysTime;
};
#endif

/* ImageUpload.h:722 */
#ifndef SOAP_TYPE___ns1__UpLoadImg_
#define SOAP_TYPE___ns1__UpLoadImg_ (39)
/* Wrapper: */
struct __ns1__UpLoadImg_ {
        /** Optional element 'ns1:UpLoadImg' of XSD type 'ns1:UpLoadImg' */
        struct _ns1__UpLoadImg *ns1__UpLoadImg;
};
#endif

/* ImageUpload.h:780 */
#ifndef SOAP_TYPE___ns1__SetCurrentBillWay_
#define SOAP_TYPE___ns1__SetCurrentBillWay_ (41)
/* Wrapper: */
struct __ns1__SetCurrentBillWay_ {
        /** Optional element 'ns1:SetCurrentBillWay' of XSD type 'ns1:SetCurrentBillWay' */
        struct _ns1__SetCurrentBillWay *ns1__SetCurrentBillWay;
};
#endif

/* ImageUpload.h:838 */
#ifndef SOAP_TYPE___ns1__GetCurrentImg_
#define SOAP_TYPE___ns1__GetCurrentImg_ (43)
/* Wrapper: */
struct __ns1__GetCurrentImg_ {
        /** Optional element 'ns1:GetCurrentImg' of XSD type 'ns1:GetCurrentImg' */
        struct _ns1__GetCurrentImg *ns1__GetCurrentImg;
};
#endif

/* ImageUpload.h:1019 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* ImageUpload.h:1019 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (45)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* ImageUpload.h:1019 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (47)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* ImageUpload.h:1019 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (50)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* ImageUpload.h:1019 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (51)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* ImageUpload.h:119 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

/* ImageUpload.h:119 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* unsigned char has binding name 'unsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (9)
#endif

/* unsigned int has binding name 'unsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (8)
#endif

/* enum xsd__boolean has binding name 'xsd__boolean' for type 'xsd:boolean' */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (51)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (50)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (47)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (45)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
#endif

/* struct _ns1__GetCurrentImgResponse has binding name '_ns1__GetCurrentImgResponse' for type '' */
#ifndef SOAP_TYPE__ns1__GetCurrentImgResponse
#define SOAP_TYPE__ns1__GetCurrentImgResponse (19)
#endif

/* struct _ns1__GetCurrentImg has binding name '_ns1__GetCurrentImg' for type '' */
#ifndef SOAP_TYPE__ns1__GetCurrentImg
#define SOAP_TYPE__ns1__GetCurrentImg (18)
#endif

/* struct _ns1__SetCurrentBillWayResponse has binding name '_ns1__SetCurrentBillWayResponse' for type '' */
#ifndef SOAP_TYPE__ns1__SetCurrentBillWayResponse
#define SOAP_TYPE__ns1__SetCurrentBillWayResponse (17)
#endif

/* struct _ns1__SetCurrentBillWay has binding name '_ns1__SetCurrentBillWay' for type '' */
#ifndef SOAP_TYPE__ns1__SetCurrentBillWay
#define SOAP_TYPE__ns1__SetCurrentBillWay (16)
#endif

/* struct _ns1__UpLoadImgResponse has binding name '_ns1__UpLoadImgResponse' for type '' */
#ifndef SOAP_TYPE__ns1__UpLoadImgResponse
#define SOAP_TYPE__ns1__UpLoadImgResponse (15)
#endif

/* struct _ns1__UpLoadImg has binding name '_ns1__UpLoadImg' for type '' */
#ifndef SOAP_TYPE__ns1__UpLoadImg
#define SOAP_TYPE__ns1__UpLoadImg (14)
#endif

/* struct _ns1__GetSysTimeResponse has binding name '_ns1__GetSysTimeResponse' for type '' */
#ifndef SOAP_TYPE__ns1__GetSysTimeResponse
#define SOAP_TYPE__ns1__GetSysTimeResponse (13)
#endif

/* struct _ns1__GetSysTime has binding name '_ns1__GetSysTime' for type '' */
#ifndef SOAP_TYPE__ns1__GetSysTime
#define SOAP_TYPE__ns1__GetSysTime (12)
#endif

/* struct xsd__base64Binary has binding name 'xsd__base64Binary' for type 'xsd:base64Binary' */
#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (53)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (52)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (46)
#endif

/* struct _ns1__GetCurrentImgResponse * has binding name 'PointerTo_ns1__GetCurrentImgResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__GetCurrentImgResponse
#define SOAP_TYPE_PointerTo_ns1__GetCurrentImgResponse (33)
#endif

/* struct _ns1__GetCurrentImg * has binding name 'PointerTo_ns1__GetCurrentImg' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__GetCurrentImg
#define SOAP_TYPE_PointerTo_ns1__GetCurrentImg (32)
#endif

/* struct _ns1__SetCurrentBillWayResponse * has binding name 'PointerTo_ns1__SetCurrentBillWayResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__SetCurrentBillWayResponse
#define SOAP_TYPE_PointerTo_ns1__SetCurrentBillWayResponse (29)
#endif

/* struct _ns1__SetCurrentBillWay * has binding name 'PointerTo_ns1__SetCurrentBillWay' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__SetCurrentBillWay
#define SOAP_TYPE_PointerTo_ns1__SetCurrentBillWay (28)
#endif

/* struct _ns1__UpLoadImgResponse * has binding name 'PointerTo_ns1__UpLoadImgResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__UpLoadImgResponse
#define SOAP_TYPE_PointerTo_ns1__UpLoadImgResponse (25)
#endif

/* struct _ns1__UpLoadImg * has binding name 'PointerTo_ns1__UpLoadImg' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__UpLoadImg
#define SOAP_TYPE_PointerTo_ns1__UpLoadImg (24)
#endif

/* struct _ns1__GetSysTimeResponse * has binding name 'PointerTo_ns1__GetSysTimeResponse' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__GetSysTimeResponse
#define SOAP_TYPE_PointerTo_ns1__GetSysTimeResponse (21)
#endif

/* struct _ns1__GetSysTime * has binding name 'PointerTo_ns1__GetSysTime' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__GetSysTime
#define SOAP_TYPE_PointerTo_ns1__GetSysTime (20)
#endif

/* unsigned char * has binding name 'PointerTounsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (10)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetSysTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetSysTime *ns1__GetSysTime, struct _ns1__GetSysTimeResponse *ns1__GetSysTimeResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpLoadImg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__UpLoadImg *ns1__UpLoadImg, struct _ns1__UpLoadImgResponse *ns1__UpLoadImgResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetCurrentBillWay(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__SetCurrentBillWay *ns1__SetCurrentBillWay, struct _ns1__SetCurrentBillWayResponse *ns1__SetCurrentBillWayResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetCurrentImg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetCurrentImg *ns1__GetCurrentImg, struct _ns1__GetCurrentImgResponse *ns1__GetCurrentImgResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetSysTime_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetSysTime *ns1__GetSysTime, struct _ns1__GetSysTimeResponse *ns1__GetSysTimeResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpLoadImg_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__UpLoadImg *ns1__UpLoadImg, struct _ns1__UpLoadImgResponse *ns1__UpLoadImgResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetCurrentBillWay_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__SetCurrentBillWay *ns1__SetCurrentBillWay, struct _ns1__SetCurrentBillWayResponse *ns1__SetCurrentBillWayResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetCurrentImg_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetCurrentImg *ns1__GetCurrentImg, struct _ns1__GetCurrentImgResponse *ns1__GetCurrentImgResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation '__ns1__GetSysTime' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__GetSysTime(struct soap*, struct _ns1__GetSysTime *ns1__GetSysTime, struct _ns1__GetSysTimeResponse *ns1__GetSysTimeResponse);
    /** Web service operation '__ns1__UpLoadImg' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__UpLoadImg(struct soap*, struct _ns1__UpLoadImg *ns1__UpLoadImg, struct _ns1__UpLoadImgResponse *ns1__UpLoadImgResponse);
    /** Web service operation '__ns1__SetCurrentBillWay' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__SetCurrentBillWay(struct soap*, struct _ns1__SetCurrentBillWay *ns1__SetCurrentBillWay, struct _ns1__SetCurrentBillWayResponse *ns1__SetCurrentBillWayResponse);
    /** Web service operation '__ns1__GetCurrentImg' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__GetCurrentImg(struct soap*, struct _ns1__GetCurrentImg *ns1__GetCurrentImg, struct _ns1__GetCurrentImgResponse *ns1__GetCurrentImgResponse);
    /** Web service operation '__ns1__GetSysTime_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__GetSysTime_(struct soap*, struct _ns1__GetSysTime *ns1__GetSysTime, struct _ns1__GetSysTimeResponse *ns1__GetSysTimeResponse);
    /** Web service operation '__ns1__UpLoadImg_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__UpLoadImg_(struct soap*, struct _ns1__UpLoadImg *ns1__UpLoadImg, struct _ns1__UpLoadImgResponse *ns1__UpLoadImgResponse);
    /** Web service operation '__ns1__SetCurrentBillWay_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__SetCurrentBillWay_(struct soap*, struct _ns1__SetCurrentBillWay *ns1__SetCurrentBillWay, struct _ns1__SetCurrentBillWayResponse *ns1__SetCurrentBillWayResponse);
    /** Web service operation '__ns1__GetCurrentImg_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__GetCurrentImg_(struct soap*, struct _ns1__GetCurrentImg *ns1__GetCurrentImg, struct _ns1__GetCurrentImgResponse *ns1__GetCurrentImgResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetSysTime(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__UpLoadImg(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SetCurrentBillWay(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetCurrentImg(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetSysTime_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__UpLoadImg_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SetCurrentBillWay_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetCurrentImg_(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
